### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by B3ni15** [lavacord/Lavacord#133]
ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (C:\Users\Beni\Documents\HunTools-bot\node_modules\lavacord\node_modules\undici\lib\fetch\response.js:507:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\Beni\Documents\HunTools-bot\node_modules\lavacord\node_modules\undici\lib\fetch\index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\Beni\Documents\HunTools-bot\node_modules\lavacord\node_modules\undici\index.js:97:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14) Promise {
  <rejected> ReferenceError: ReadableStream is not defined
      at Object.<anonymous> (C:\Users\Beni\Documents\HunTools-bot\node_modules\lavacord\node_modules\undici\lib\fetch\response.js:507:3)
      at Module._compile (node:internal/modules/cjs/loader:1198:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
      at Module.load (node:internal/modules/cjs/loader:1076:32)
      at Function.Module._load (node:internal/modules/cjs/loader:911:12)
      at Module.require (node:internal/modules/cjs/loader:1100:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at Object.<anonymous> (C:\Users\Beni\Documents\HunTools-bot\node_modules\lavacord\node_modules\undici\lib\fetch\index.js:11:5)
      at Module._compile (node:internal/modules/cjs/loader:1198:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
      at Module.load (node:internal/modules/cjs/loader:1076:32)
      at Function.Module._load (node:internal/modules/cjs/loader:911:12)
      at Module.require (node:internal/modules/cjs/loader:1100:19)
      at require (node:internal/modules/cjs/helpers:119:18)
      at Object.<anonymous> (C:\Users\Beni\Documents\HunTools-bot\node_modules\lavacord\node_modules\undici\index.js:97:19)
      at Module._compile (node:internal/modules/cjs/loader:1198:14)
}

**Comment by PapiOphidian** [comment]
Lavacord requires a node.js version >= v18 as that's when web streams were officially part of node.js, though I believe v17 also works. I noticed I forgot to update the package.json from node.js v10, so I will do that as soon as I can

**Comment by PapiOphidian** [comment]
"fixed" in 2.1.4-v4
